[package]
name = "verco"
version = "0.1.0"
authors = ["Matheus Lessa <matheuslessarodrigues@gmail.com>"]

[[bin]]
name = "verco"
path = "src/main.rs"

[dependencies]
termion = { git = "https://github.com/mcgoo/termion", branch = "windows" }
rustyline = "1.0.0"

