[package]
name = "verco"
version = "0.3.1"
authors = ["Matheus Lessa <matheuslessarodrigues@gmail.com>"]
exclude = [
    "images/*",
]

[[bin]]
name = "verco"
path = "src/main.rs"

[dependencies]
termion = { git = "https://github.com/mcgoo/termion", branch = "windows" }
rustyline = "1.0.0"

