[package]
name = "verco"
version = "1.1.0"
authors = ["Matheus Lessa <matheuslessarodrigues@gmail.com>"]
edition = "2018"
exclude = [
    "images/*",
]
description = "A simple Git/Hg version control client based on keyboard shortcuts"
license = "MIT"

[[bin]]
name = "verco"
path = "src/main.rs"

[dependencies]
crossterm = "0.9"
rustyline = "2.1.0"
