[package]
name = "verco"
version = "0.1.0"
authors = ["Matheus Lessa <matheuslessarodrigues@gmail.com>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
termion = { git = "https://github.com/mcgoo/termion", branch = "windows" }
liner = { git = "https://github.com/joeyAcc/liner", branch = "windows" }

[[bin]]
name = "verco"
path = "src/main.rs"
